### PR TITLE
Changes to .net standard and enables appveyor build.

### PR DESCRIPTION
**Pull request by toadicusrex**

### CODE REVIEW

**Comment by toadicusrex** [comment]
This uses the good work by  AdaskoTheBeAsT and modifies the csproj and the appveyor build script so that the project can be built.

**Comment by toadicusrex** [comment]
Stupid touchpad....

**Comment by toadicusrex** [comment]
I'm really anxious to be able to target .net standard; I'm happy to do whatever work is necessary to get this published.

**Comment by AdaskoTheBeAsT** [comment]
Thanks @toadicusrex for solving appveyor thingy - I lost on it ;)

**Pull request merged**
